/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.spbstu.telematics.bitbotx;

import org.junit.jupiter.api.Test;
import org.springframework.web.reactive.function.client.WebClient;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class PriceFetcherTest {
    
    @Test
    void testPriceFetcherCreation() {
        WebClient.Builder webClientBuilder = WebClient.builder();
        PriceFetcher priceFetcher = new PriceFetcher(webClientBuilder, "test-key", "test-secret");
        assertNotNull(priceFetcher);
    }
}
